### ISSUE TITLE
React group project: set up your Kanban board

### ISSUE THREAD

**Issue by K0ppai** [K0ppai/space_travelers#49]
Hello reviewers,
we have two members @K0ppai & @abdozayan12 in this project.
This is the [project link](https://github.com/K0ppai/space_travelers/projects/1).

**Comment by shella12** [comment]
Hi @K0ppai and @abdozayan12, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- All tasks are assigned ✅ 
- Tasks distributed fairly ✅   

## Required Changes ♻️


- [ ] Great 👍 job on setting up the kanban and fairly distributing the tasks. However I have noticed that there are two cards for the group task `[1pt] Create app and install basic dependencies - Setup (group task) #48` in your kanban. Please delete the duplicated task  `[1pt] Create app and install basic dependencies - Setup (group task) #48` from your kanban and then you'll be all set 😄 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binhussen** [comment]
Hi @shella12, @K0ppai and @abdozayan12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Based template board ✔️
- Fairly Distributed Task ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
